#!/usr/bin/env ruby

PROG="freecell"
VIEW="open"
#FLAGS==--yourflags profiling/toydata.xml

do_configure = ARGV.size == 0 || ARGV[0] == "-c"
do_run = ARGV.size == 0 || (ARGV.size >= 1 and ARGV[0] == "-r")

opts = "-h"

opts = ARGV[1] if ARGV.size == 2

if do_configure
    system("cabal configure --enable-library-profiling --enable-executable-profiling")
    system("cabal build #{PROG}")
end

if do_run
    system("rm ./freecell.*")
    system("dist/build/#{PROG}/#{PROG} +RTS #{opts}")
    sleep 0.3
    system("hp2ps -c #{PROG}.hp")
    sleep 0.3
    system("#{VIEW} #{PROG}.ps")
end
