# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-22.12

# Local packages, usually specified by relative directory name
packages:
- 'core'
- 'GLFW'
- 'SDL'
- 'iOS'
- 'FRP'
- 'Example/Shooter'
- '../oss/sdl2'

allow-newer: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- reactive-banana-1.3.1.0
- wavefront-0.7.1.4
- vulkan-3.23
- vulkan-utils-0.5.10.1
- VulkanMemoryAllocator-0.10.4
- derive-storable-0.3.1.0
- acquire-0.2.0.1
- ki-1.0.1.1
# - dear-imgui-2.1.0
- git: https://github.com/asivitz/dear-imgui.hs.git
  commit: 0be78f05caf234e5ac72387ae26612bc4ea642cd
- git: https://github.com/fieldstrength/aeson-deriving.git
  commit: e6e1f5066ebf1f37c10687e9bc90e5b0d3b22b0c

# Override default flag values for local packages and extra-deps
flags:
  dear-imgui:
    opengl3: false
    vulkan: true
    sdl: true
    glfw: true

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

extra-lib-dirs:
- /usr/local/lib
