name:                Hickory
version:             0.1.0.0
synopsis:            Tools for building OpenGL based programs in Haskell
homepage:            https://github.com/asivitz/Hickory
description:         Please see README.md
license:             MIT
license-file:        LICENSE
author:              Axis Sivitz
maintainer:          aosivitz@gmail.com
copyright:           2017 Axis Sivitz

ghc-options:
    - -Wall

extra-source-files:
    - Readme.md

default-extensions:
    - NamedFieldPuns
    - Rank2Types
    - BangPatterns
    - OverloadedStrings
    - ScopedTypeVariables
    - LambdaCase
    - TupleSections
    - ViewPatterns
    - BlockArguments
    - RecordWildCards

dependencies:
    - JuicyPixels
    - JuicyPixels-extra
    - MonadRandom
    - OpenGLRaw
    - attoparsec
    - base
    - containers
    - groom
    - hashable
    - lens
    - linear
    - megaparsec
    - mtl
    - random
    - rawstring-qm
    - reactive-banana
    - scientific
    - text
    - time
    - unordered-containers
    - vector
    - wavefront
    - binary
    - vector-binary-instances
    - managed
    - vulkan
    - vulkan-utils
    - VulkanMemoryAllocator
    - bytestring

when:
    - condition: os(osx)
      cc-options:         -F/System/Library/Frameworks

library:
  exposed-modules:
    - Hickory.Camera
    - Hickory.Color
    - Hickory.Graphics
    - Hickory.Graphics.Debug
    - Hickory.Graphics.DeferredRendering
    - Hickory.Graphics.DrawText
    - Hickory.Graphics.Mesh
    - Hickory.Graphics.Drawing
    - Hickory.Graphics.GLSupport
    - Hickory.Graphics.MatrixMonad
    - Hickory.Graphics.SSAO
    - Hickory.Graphics.Shader
    - Hickory.Graphics.ShaderMonad
    - Hickory.Graphics.StockShaders
    - Hickory.Graphics.Textures
    - Hickory.Graphics.Uniforms
    - Hickory.Graphics.VAO
    - Hickory.Graphics.Framebuffer
    - Hickory.Input
    - Hickory.Math
    - Hickory.Math.Interpolate
    - Hickory.Math.Matrix
    - Hickory.Math.Vector
    - Hickory.Math.VectorMatrix
    - Hickory.ModelLoading.Animation
    - Hickory.ModelLoading.Bvh
    - Hickory.ModelLoading.DirectX
    - Hickory.ModelLoading.DirectXModel
    - Hickory.ModelLoading.Parsing
    - Hickory.ModelLoading.Wavefront
    - Hickory.ModelLoading.Packed
    - Hickory.Platform
    - Hickory.Resources
    - Hickory.Serialize
    - Hickory.Text.Font
    - Hickory.Text.Text
    - Hickory.Types
    - Hickory.Utils.Projection
    - Hickory.Utils.Utils
    - Hickory.Vulkan.Vulkan
    - Hickory.Vulkan.Mesh
    - Hickory.Vulkan.Material
    - Hickory.Vulkan.Textures
    - Hickory.Vulkan.Monad
    - Hickory.Vulkan.Text

executables:
  pack-model:
    source-dirs:
      - pack-model/
    main: main.hs
    dependencies:
      - Hickory
      - filepath

tests:
    hickory-test:
        main:            Main.hs
        source-dirs:     test
        dependencies:
            - base >=4.7 && <5
            - test-framework
            - test-framework-hunit
            - HUnit
            - HUnit-approx >= 1.0
            - Hickory
            - containers >= 0.5 && < 0.6
