name:                Hickory
version:             0.1.0.0
synopsis:            Tools for building OpenGL based programs in Haskell
homepage:            https://github.com/asivitz/Hickory
description:         Please see README.md
license:             MIT
license-file:        LICENSE
author:              Axis Sivitz
maintainer:          aosivitz@gmail.com
copyright:           2017 Axis Sivitz

ghc-options:
    - -Wall

extra-source-files:
    - Readme.md

default-extensions:
    - NamedFieldPuns
    - Rank2Types
    - BangPatterns
    - OverloadedStrings
    - ScopedTypeVariables
    - LambdaCase
    - TupleSections
    - ViewPatterns
    - BlockArguments
    - RecordWildCards
    - GHC2021

dependencies:
    - JuicyPixels
    - JuicyPixels-extra
    - MonadRandom
    - OpenGLRaw
    - VulkanMemoryAllocator
    - acquire
    - attoparsec
    - aeson
    - deriving-aeson
    - base
    - binary
    - bytestring
    - containers
    - derive-storable
    - vector-sized
    - finite-typelits
    - generic-lens
    - groom
    - hashable
    - lens
    - linear
    - managed
    - megaparsec
    - mtl
    - random
    - rawstring-qm
    - reactive-banana
    - scientific
    - text
    - time
    - unordered-containers
    - uuid
    - vector
    - vector-binary-instances
    - vulkan
    - vulkan-utils
    - wavefront
    - directory
    - bitwise-enum
    - safe
    - ghc-compact
    - wide-word

when:
    - condition: os(osx)
      cc-options:         -F/System/Library/Frameworks

library:
  verbatim:
    default-language: GHC2021

  exposed-modules:
    - Hickory.Camera
    - Hickory.Color
    - Hickory.GameLoop
    - Hickory.Graphics
    - Hickory.Graphics.Debug
    - Hickory.Graphics.DeferredRendering
    - Hickory.Graphics.DrawText
    - Hickory.Graphics.Mesh
    - Hickory.Graphics.Drawing
    - Hickory.Graphics.GLSupport
    - Hickory.Graphics.MatrixMonad
    - Hickory.Graphics.SSAO
    - Hickory.Graphics.Shader
    - Hickory.Graphics.ShaderMonad
    - Hickory.Graphics.StockShaders
    - Hickory.Graphics.Textures
    - Hickory.Graphics.Uniforms
    - Hickory.Graphics.VAO
    - Hickory.Graphics.Framebuffer
    - Hickory.Input
    - Hickory.Math
    - Hickory.Math.Interpolate
    - Hickory.Math.Matrix
    - Hickory.Math.Vector
    - Hickory.Math.VectorMatrix
    - Hickory.Math.Bezier
    - Hickory.ModelLoading.Animation
    - Hickory.ModelLoading.Bvh
    - Hickory.ModelLoading.DirectX
    - Hickory.ModelLoading.DirectXModel
    - Hickory.ModelLoading.Parsing
    - Hickory.ModelLoading.Wavefront
    - Hickory.ModelLoading.Packed
    - Hickory.Resources
    - Hickory.Serialize
    # - Hickory.Text.ParseFnt
    - Hickory.Text.ParseJson
    - Hickory.Text.Text
    - Hickory.Text
    - Hickory.Text.Types
    - Hickory.Types
    - Hickory.Utils.Projection
    - Hickory.Utils.Utils
    - Hickory.Vulkan.Vulkan
    - Hickory.Vulkan.Mesh
    - Hickory.Vulkan.Material
    - Hickory.Vulkan.DescriptorSet
    - Hickory.Vulkan.Textures
    - Hickory.Vulkan.Monad
    - Hickory.Vulkan.Text
    - Hickory.Vulkan.DynamicMesh
    - Hickory.Vulkan.Framing
    - Hickory.Vulkan.Frame
    - Hickory.Vulkan.Instance
    - Hickory.Vulkan.Utils
    - Hickory.Vulkan.RenderPass
    - Hickory.Vulkan.StockMesh
    - Hickory.Vulkan.StockTexture
    - Hickory.Vulkan.PostProcessing
    - Hickory.Vulkan.RenderTarget
    - Hickory.Vulkan.Forward.ObjectPicking
    - Hickory.Vulkan.Forward.Renderer
    - Hickory.Vulkan.Forward.Types
    - Hickory.Vulkan.Forward.Lit
    - Hickory.Vulkan.Forward.ShadowPass
    - Hickory.Vulkan.Forward.DrawingPrimitives
    - Hickory.Vulkan.Forward.ShaderDefinitions
    - Hickory.Vulkan.Types

executables:
  pack-model:
    verbatim:
      default-language: GHC2021
    source-dirs:
      - pack-model/
    main: main.hs
    dependencies:
      - Hickory
      - filepath

tests:
    hickory-test:
        verbatim:
          default-language: GHC2021
        main:            Main.hs
        source-dirs:     test
        dependencies:
            - base >=4.7 && <5
            - test-framework
            - test-framework-hunit
            - HUnit
            - HUnit-approx >= 1.0
            - Hickory
            - containers >= 0.5 && < 0.6
