name:                SmallDep

default-extensions:
  - OverloadedStrings

dependencies:
    - base
    - rawstring-qm
    - text
    - dear-imgui
    - vulkan-utils

library:
  verbatim:
    default-language: GHC2021

  exposed-modules:
    - SmallDep.Foo
