name:                Small

default-extensions:
  - OverloadedStrings

dependencies:
    - base
    - rawstring-qm
    - text

library:
  verbatim:
    default-language: GHC2021

  exposed-modules:
    - Small.Foo
