name:                Small

default-extensions:
  - OverloadedStrings

dependencies:
    - base
    - rawstring-qm
    - text
    - dear-imgui
    - vulkan-utils
    - SmallDep
    - Hickory

library:
  verbatim:
    default-language: GHC2021

  exposed-modules:
    - Small.Foo

  other-modules:
    - Small.QQ
