name:                Small

default-extensions:
  - OverloadedStrings

dependencies:
    - base
    - rawstring-qm
    # - sdl2
    - text
    - dear-imgui

library:
  verbatim:
    default-language: GHC2021

  exposed-modules:
    - Small.Foo
