name:                Small

default-extensions:
  - OverloadedStrings

dependencies:
    - base
    - rawstring-qm
    - text
    - dear-imgui
    - vulkan-utils
    - gltf-loader
    - yoga
    - file-embed
    - Hickory
    - Hickory-SDL

library:
  verbatim:
    default-language: GHC2021

  exposed-modules:
    - Small.Foo

  other-modules:
    - Small.QQ
