name:                Hackory

ghc-options:
    - -Wall
    - -Werror=incomplete-patterns
    - -Wunused-packages
    - -Werror=unused-packages

extra-source-files:
    - Readme.md

default-extensions:
    - NamedFieldPuns
    - Rank2Types
    - BangPatterns
    - OverloadedStrings
    - ScopedTypeVariables
    - LambdaCase
    - TupleSections
    - ViewPatterns
    - BlockArguments
    - RecordWildCards
    - GHC2021

dependencies:
    - base
    - dear-imgui
    - generic-lens
    - hashable
    - lens
    - linear
    - text
    - unordered-containers

flags:
  production:
    description: Enable production mode
    manual: true
    default: false

when:
    - condition: os(osx)
      cc-options:         -F/System/Library/Frameworks

library:
  verbatim:
    default-language: GHC2021
  when:
    - condition: "flag(production)"
      cpp-options: -DPRODUCTION

  exposed-modules:
    - Hickory.ImGUI.ImGUI
    - Hickory.Editor
    - Hickory.Editor.Types
