name:                Hackory

ghc-options:
    - -Wall
    - -Werror=incomplete-patterns
    - -Wunused-packages
    - -Werror=unused-packages

extra-source-files:
    - Readme.md

default-extensions:
    - NamedFieldPuns
    - Rank2Types
    - BangPatterns
    - OverloadedStrings
    - ScopedTypeVariables
    - LambdaCase
    - TupleSections
    - ViewPatterns
    - BlockArguments
    - RecordWildCards
    - GHC2021

dependencies:
    - VulkanMemoryAllocator
    - acquire
    - base
    - bytestring
    - dear-imgui
    - derive-storable
    - generic-lens
    - hashable
    - lens
    - linear
    - text
    - unordered-containers
    - uuid
    - vector
    - vulkan
    - vulkan-utils

flags:
  production:
    description: Enable production mode
    manual: true
    default: false

when:
    - condition: os(osx)
      cc-options:         -F/System/Library/Frameworks

library:
  verbatim:
    default-language: GHC2021
  when:
    - condition: "flag(production)"
      cpp-options: -DPRODUCTION

  exposed-modules:
    - Hickory.Math
    - Hickory.Math.Matrix
    - Hickory.Math.Vector
    - Hickory.Math.VectorMatrix
    - Hickory.Types
    - Hickory.Vulkan.Vulkan
    - Hickory.Vulkan.Framing
    - Hickory.Vulkan.Frame
    - Hickory.Vulkan.Instance
    - Hickory.Vulkan.Utils
    - Hickory.Vulkan.RenderPass
    - Hickory.Vulkan.RenderTarget
    - Hickory.Vulkan.Types
    - Hickory.ImGUI.Helpers
    - Hickory.ImGUI.ImGUI
    - Hickory.Editor
    - Hickory.Editor.Types
