name:                Hackory

ghc-options:
    - -Wall
    - -Wunused-packages
    - -Werror=unused-packages
    - -O0

extra-source-files:
    - Readme.md

default-extensions:
    - NamedFieldPuns
    - Rank2Types
    - OverloadedStrings
    - ScopedTypeVariables
    - TupleSections
    - BlockArguments
    - RecordWildCards
    - GHC2021

dependencies:
    - base
    - dear-imgui
    - generic-lens
    - hashable
    - linear
    - unordered-containers

library:
  verbatim:
    default-language: GHC2021

  exposed-modules:
    - Hickory.ImGUI
    - Hickory.Editor
