name:                Hackory

ghc-options:
    - -Wall
    - -Wunused-packages
    - -Werror=unused-packages
    - -O0

extra-source-files:
    - Readme.md

default-extensions:
    - GHC2021

dependencies:
    - base
    - dear-imgui
    - generic-lens
    - linear

library:
  verbatim:
    default-language: GHC2021

  exposed-modules:
    - Hickory.ImGUI
    - Hickory.Editor
